apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: myjsons.testing.io
spec:
  group: testing.io
  names:
    kind: MyJson
    plural: myjsons
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        description: This is a boilerplate custom resource used for testing of MyJson resources.
        properties:
          spec:
            type: object
            x-kubernetes-preserve-unknown-fields: true
        type: object
    served: true
    storage: true